use PTTKHTTT_QLKS
go


DROP PROCEDURE IF EXISTS LayDSPhongDeDat
go
create PROCEDURE LayDSPhongDeDat
    @StartDate DATE,
    @EndDate DATE
AS
BEGIN
    SELECT P.MAPHONG, P.LOAIPHONG, P.HANG, P.GIA, P.TINHTRANG
    FROM PHONG P
    WHERE P.MAPHONG NOT IN (
        SELECT CTP.MAPHONG
        FROM CHITIETPHIEUDATPHONG CTP
        INNER JOIN PHIEUDATPHONG PDP ON CTP.MAPDP = PDP.MAPDP
        --WHERE NGAYNHANPHONG > GETDATE() AND ((PDP.NGAYNHANPHONG >= @StartDate AND PDP.NGAYNHANPHONG< @EndDate)
        --    OR (PDP.NGAYTRAPHONG > @StartDate AND PDP.NGAYTRAPHONG<= @EndDate))
        WHERE 
		(NGAYTRAPHONG > @StartDate and NGAYNHANPHONG  < @StartDate) or 
		(NGAYNHANPHONG >= @StartDate and NGAYTRAPHONG <= @EndDate) or
		(NGAYNHANPHONG < @EndDate and NGAYTRAPHONG >= @EndDate) or
		(NGAYNHANPHONG <= @StartDate and NGAYTRAPHONG >= @EndDate)

		 )

END
go
exec LayDSPhongDeDat '2023-07-03' , '2023-07-04'



DROP PROCEDURE IF EXISTS QLPhong_TraCuuPhong
go
create proc QLPhong_TraCuuPhong @keyword nvarchar(20)
as
begin try
	select *
	from PHONG
	where
		(MAPHONG like '%'+ @keyword +'%' or
		LOAIPHONG like '%'+  @keyword +'%' or
		HANG like '%'+  @keyword +'%' or
		GIA like '%'+  @keyword +'%' or
		TINHTRANG like '%'+  @keyword +'%' )
end try
begin catch
end catch
go





--them khach hang
DROP PROCEDURE IF EXISTS USP_THEMKHACHHANG
go
CREATE PROCEDURE USP_THEMKHACHHANG
	@HOTEN NVARCHAR(50), 
	@CCCD CHAR(12),
	@SDT CHAR(11), 
	@DIACHI NVARCHAR(60), 
	@FAXID INT, 
	@EMAIL VARCHAR(50)
AS
BEGIN
    -- Kiểm tra TON TAI
	IF EXISTS(SELECT * FROM KHACHHANG WHERE CCCD = @CCCD)
		BEGIN
			select (SELECT TOP 1 MAKH FROM KHACHHANG WHERE CCCD = @CCCD)
		END
	DECLARE @MAKH INT;
	select @MAKH = max(maKH) + 1 from KHACHHANG;
    -- THEM PHONG
	INSERT INTO KHACHHANG (MAKH, HOTEN, CCCD, SDT, DIACHI, FAXID, EMAIL) 
	VALUES (@MAKH, @HOTEN, @CCCD, @SDT, @DIACHI, @FAXID, @EMAIL) 
	select @MAKH
END
GO





--THEM PHIEU DAT PHONG
DROP PROCEDURE IF EXISTS USP_LT_TAOPHIEUDATPHONG
go
--thanh toán tiền cọc 30% khi tạo phiếu đặt phòng
CREATE PROCEDURE USP_LT_TAOPHIEUDATPHONG
	@NGAYNHANPHONG DATE,
	@NGAYTRAPHONG DATE,
	@MAKH INT,
	@MANV INT
AS
BEGIN
	DECLARE @MAPDP_ INT;
	select @MAPDP_ = max(MAPDP) + 1 from PHIEUDATPHONG;
	INSERT INTO PHIEUDATPHONG (MAPDP, NGAYLAP, NGAYNHANPHONG, NGAYTRAPHONG, MAKH, MANV)
	VALUES (@MAPDP_, GETDATE(), @NGAYNHANPHONG, @NGAYTRAPHONG, @MAKH, @MANV)
	select @MAPDP_
END
GO


DROP FUNCTION IF EXISTS uf_LT_TTCOC_HOADON
go

CREATE FUNCTION uf_LT_TTCOC_HOADON
( @MAPDP INT )
RETURNS INT
AS
BEGIN
	--KHOI TAO
	DECLARE @TONGTIEN INT;
	SET @TONGTIEN = 0;
	SELECT @TONGTIEN = SUM(P.GIA) 
	FROM PHONG P JOIN CHITIETPHIEUDATPHONG CTP ON P.MAPHONG = CTP.MAPHONG
	WHERE CTP.MAPDP = @MAPDP
	SET @TONGTIEN = ISNULL(@TONGTIEN, 0);
	RETURN @TONGTIEN;
END;
go
--TEST
--SELECT dbo.uf_LT_TTCOC_HOADON(1) TONGTIENCOC
UPDATE HOADON
SET TONGTIEN = DBO.uf_LT_TTCOC_HOADON(MAPDP)
go



DROP FUNCTION IF EXISTS uf_LT_CNTONGTIEN_HOADON
go
CREATE FUNCTION uf_LT_CNTONGTIEN_HOADON
( @MAHD INT )
RETURNS INT
AS
BEGIN
	--KHOI TAO
	DECLARE @TONGTIEN INT;
	DECLARE @TIENPHONG INT;
	DECLARE @TIENDV INT;
	SET @TONGTIEN = 0;
	--TINH 70% TIEN PHONG
	SELECT @TIENPHONG = SUM(P.GIA) 
	FROM PHONG P JOIN CHITIETPHIEUDATPHONG CTP ON P.MAPHONG = CTP.MAPHONG
	JOIN HOADON HD ON CTP.MAPDP = HD.MAPDP
	WHERE HD.MAHD = @MAHD;
	SET @TIENPHONG = ISNULL(@TIENPHONG, 0);
	--TINH TIEN DICH VU
	SELECT @TIENDV = SUM(DV.GIA*PDDV.SOLUONG) 
	FROM DICHVU DV JOIN PDT_DICHVU PDDV ON DV.MADV = PDDV.MADV
	JOIN HOADON HD ON PDDV.MAPDP = HD.MAPDP
	WHERE HD.MAHD = @MAHD;
	SET @TIENDV = ISNULL(@TIENDV, 0);
	--TINH TONG TIEN
	SET @TONGTIEN = @TIENDV + @TIENPHONG;
	RETURN @TONGTIEN;
END;
go



DROP PROCEDURE IF EXISTS USP_LT_THANHTOANCOC
go
--thanh toán tiền cọc 30% khi tạo phiếu đặt phòng
CREATE PROCEDURE USP_LT_THANHTOANCOC
     @MAPDP INT
AS
BEGIN
    -- Kiểm tra tham số @MAPDP không null
    IF @MAPDP IS NULL
    BEGIN
        select -1
        RETURN
    END
	IF NOT EXISTS(SELECT * 
						FROM PHIEUDATPHONG  
						WHERE MAPDP = @MAPDP)
			BEGIN
				--select 'KHONG TON TAI PHIEU DAT PHONG.'
				select -1
				RETURN
			END
	DECLARE @TIENPHONG INT
	SElect @TIENPHONG = DBO.uf_LT_TTCOC_HOADON(@MAPDP);
	IF @TIENPHONG = 0
		BEGIN
			-- lỗi không tính được tiền
			select -2
			RETURN
		END

	DECLARE @MAHD_ INT;
	DECLARE @MANV_ INT;
	SELECT @MANV_ = MANV FROM PHIEUDATPHONG WHERE MAPDP = @MAPDP;
	select @MAHD_ = max(mahd) + 1 from hoadon;
	if exists (select * from HOADON where MAPDP = @MAPDP)
	begin
		return -3 
	end
	INSERT INTO HOADON (MAHD, NGAYLAP, MAPDP, TONGTIEN, TinhTrangTT, MANV) 
	VALUES (@MAHD_, GETDATE(), @MAPDP, @TIENPHONG, N'Đã cọc', @MANV_); --???MANV
	select @MAHD_;
END
GO
---

